### ISSUE TITLE
Meta: important issues for 2.0 RTM

### ISSUE THREAD

**Issue by jods4** [aurelia/webpack-plugin#112]
I am using this issue to list issues I've seen in our repos that I think should be closed before we officially go from 2.0 RC to RTM.

- [ ] #109 The CLI template for DLL is missing `AureliaPlugin`.
- [ ] aurelia/templating#549 + aurelia/dialog#283 critical issue with unwanted custom elements being created. The bug has existed for a long time but combined with Webpack renaming of exports it leads to `<a>` or `<b>` being custom elements!
- [ ] aurelia/pal#21 make sure all core libs work well out-of-the-box (almost complete)
- [ ] Add docs to hub
- [ ] Update skeleton, cli templates, others?

Don't hesitate to comment if you find other important bugs.

**Comment by niieani** [comment]
I've fixed remaining skeleton issues.

One thing to keep in mind is the automatic babel-polyfill still breaking aurelia-polyfill. We should probably do something about this before RTM.

**Comment by jods4** [comment]
@niieani I'm planning to try to ease polyfilling in RC-3.

That said wasn't the issue with babel-polyfill an imcompatibility with polyfills, i.e. it should come down to configuration?

**Comment by niieani** [comment]
@jods4 The thing is, one either uses babel-polyfill or one doesn't. Not sure if there any configuration that could turn off that specific, faulty polyfill from being included.

**Comment by jods4** [comment]
I mean: if you include babel-polyfill and disable aurelia-polyfill (there's a webpack option for that) you should be fine?

**Comment by niieani** [comment]
I guess so, but you mentioned it wouldn't be possible because of the order in which Aurelia is loaded (entrypoints get loaded too late).

**Comment by jods4** [comment]
It's possible but complicated in RC2, that's what I'd like to improve for RC3.

**Comment by niieani** [comment]
OK! Sounds good.

**Comment by JeroenVinke** [comment]
Should [aurelia-testing](https://github.com/aurelia/testing/blob/master/src/aurelia-testing.js#L8-L9) use `PLATFORM.moduleName` as well?

**Comment by niieani** [comment]
@JeroenVinke that depends if you run it under NodeJS (like testing via Jest) or in the browser through Webpack (like the Karma testing in Skeleton). To be safe, it's good to always wrap your module paths in `PLATFORM.moduleName`.

**Comment by JeroenVinke** [comment]
@niieani that makes sense. The CLI uses aurelia-testing in the browser: https://github.com/aurelia/cli/blob/master/lib/resources/src/main.ts#L13-L15. I was hoping that we could the same for the webpack applications that it generates, This works fine for now though:

```
    new ModuleDependenciesPlugin({
      "aurelia-testing": [ "./compile-spy", "./view-spy" ]
    }),
```

**Comment by jods4** [comment]
You can safely use `moduleName` everywhere, because `aurelia-pal` actually implements it as:
```ts
function moduleName(id: string, options?: object) {
  return id;
}
```

**Comment by jods4** [comment]
@niieani Better entry point management is committed to RC3 branch. Now, if you include babel polyfills in the entry point hopefully it should work fine. Would be nice to get a confirmation. On top of that disabling Aurelia polyfills should also work.

**Comment by kevmeister68** [comment]
In my experimentation, core-js also breaks aurelia-polyfills with respect to the Map polyfill from memory.

**Comment by valichek** [comment]
@jods4 trying to use `layoutView` in `routes`
tried
```
{ route: 'some',  moduleId: PLATFORM.moduleName('./pages/empty'), layoutView: PLATFORM.moduleName('./pages/_resources/layout-main.html')}
```
and
```
{ route: 'some',  moduleId: PLATFORM.moduleName('./pages/empty'), layoutView: './pages/_resources/layout-main.html'}
```
no difference, still getting error `Error: Unable to find module with ID: ./pages/_resources/layout-main.html`

How to fix it?

**Comment by valichek** [comment]
So I fixed it with `PLATFORM.moduleName('pages/_resources/layout-main.html')`, is it bug?

**Comment by jods4** [comment]
@valichek 
Thanks for the report.

Relative paths `./` sometimes work differently in `aurelia-loader` at runtime and Webpack, which leads to annoying errors. This is why I advise to use absolute paths like `pages/_resources/layout-main.html` as it works more consistently.

That said, I think you might have dug a real bug here, likely in the router code.
What is nagging me is that the loader is looking for `./pages/...`. Notice the dot in front. At this point, the loader should be trying to load a normalized (absolute) module id, so my guess is that normalization is missing from Aurelia code somewhere.

I'll try to get someone who knows this code better than I do to have a look.

Anyway, you're better off using absolute names in your Webpack application. ;)

**Comment by valichek** [comment]
@jods4 sure, another thing is that I got the example of including modules from webpack skeleton. So it's better to fix this in skeleton too https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/src/app.js#L7-L9
@niieani, please, check it

**Comment by Alexander-Taran** [comment]
@bigopon RTM happened..
